version: '3.1'

services:

  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: techinsiders
      MYSQL_DATABASE: "ibank"
    ports:
      - "3306:3306"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8888:8080
